//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by Roslyn code generator.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodeGeneration.GenerationResult.Roslyn
{
    public class Buffallo
    {
        public Buffallo(string name)
        {
            Name = name;
        }

        public string Name
        {
            get;
            set;
        }

        public int NumberOfLegs => 4;
    }
}