//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by Roslyn code generator.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CodeGeneration.GenerationResult.Roslyn
{
    internal partial class Student : Person, IStudent
    {
        private int kredits;
        public Student(string neptunCode, string name): base(name)
        {
            NeptunCode = neptunCode;
        }

        public string NeptunCode
        {
            get;
        }

        public int Kredits
        {
            get
            {
                return kredits;
            }

            set
            {
                kredits = value;
            }
        }
    }
}