//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.GenerationResult.T4.HostSpecific
{
    public interface IStudent
    {

        string NeptunCode { get; }

        int Kredits { get; set;}

        string Name { get; }

        int Age { get; set;}
    }
}

