//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.GenerationResult.T4.HostSpecific
{
    internal partial class Person :
        IPerson
    {
        private int age;

        public Person(
            string name)
        {
            Name = name;
        }

        public string Name { get; }

        public int Age
        {
            get
            {
                return age;
            }

            set
            {
                age = value;
            }
        }
    }
}
