//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.GenerationResult.CodeDOM
{
    
    
    public class Buffallo
    {
        
        public Buffallo(string name)
        {
            Name = names;
        }
        
        // Name of the animal
        public virtual string Name
        {
            get
            {
            }
            set
            {
            }
        }
        
        public virtual void NumberOfLegs
        {
            get
            {
                return 4;
            }
        }
    }
}
