//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.GenerationResult.CodeDOM
{
    
    
    public partial class Person : IPerson
    {
        
        private int age;
        
        public Person(string name)
        {
            Name = name;
        }
        
        public virtual string Name
        {
            get
            {
            }
        }
        
        public virtual int Age
        {
            get
            {
                return this.age;
            }
            set
            {
                this.age = value;
            }
        }
    }
}
