//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.GenerationResult.CodeDOM
{
    
    
    public partial class Student : Person, IStudent
    {
        
        private int kredits;
        
        public Student(string neptunCode, string name) : 
                base(name)
        {
            NeptunCode = neptunCode;
        }
        
        public virtual string NeptunCode
        {
            get
            {
            }
        }
        
        public virtual int Kredits
        {
            get
            {
                return this.kredits;
            }
            set
            {
                this.kredits = value;
            }
        }
    }
}
