//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace CodeGeneration.DSL
{
	/// <summary>
	/// DomainRelationship WorldHasAnimals
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("CodeGeneration.DSL.WorldHasAnimals.DisplayName", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("CodeGeneration.DSL.WorldHasAnimals.Description", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::CodeGeneration.DSL.DSLDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("faceaa50-72a5-4ebb-bc95-66c6e59e5fab")]
	public partial class WorldHasAnimals : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// WorldHasAnimals domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfaceaa50, 0x72a5, 0x4ebb, 0xbc, 0x95, 0x66, 0xc6, 0xe5, 0x9e, 0x5f, 0xab);
	
				
		/// <summary>
		/// Constructor
		/// Creates a WorldHasAnimals link in the same Partition as the given World
		/// </summary>
		/// <param name="source">World to use as the source of the relationship.</param>
		/// <param name="target">Animal to use as the target of the relationship.</param>
		internal WorldHasAnimals(World source, Animal target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(WorldHasAnimals.WorldDomainRoleId, source), new DslModeling::RoleAssignment(WorldHasAnimals.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public WorldHasAnimals(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public WorldHasAnimals(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public WorldHasAnimals(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public WorldHasAnimals(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region World domain role code
		
		/// <summary>
		/// World domain role Id.
		/// </summary>
		public static readonly global::System.Guid WorldDomainRoleId = new global::System.Guid(0x9a4fa787, 0xc83c, 0x44a5, 0x92, 0x07, 0xed, 0x01, 0x1a, 0x45, 0xe9, 0x11);
		
		/// <summary>
		/// DomainRole World
		/// </summary>
		[DslDesign::DisplayNameResource("CodeGeneration.DSL.WorldHasAnimals/World.DisplayName", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("CodeGeneration.DSL.WorldHasAnimals/World.Description", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Animals", PropertyDisplayNameKey="CodeGeneration.DSL.WorldHasAnimals/World.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("9a4fa787-c83c-44a5-9207-ed011a45e911")]
		internal virtual World World
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (World)DslModeling::DomainRoleInfo.GetRolePlayer(this, WorldDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, WorldDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access World of a Animal
		/// <summary>
		/// Gets World.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static World GetWorld(Animal element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as World;
		}
		
		/// <summary>
		/// Sets World.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static void SetWorld(Animal element, World newWorld)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newWorld);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0x3224416b, 0x0762, 0x4a1a, 0x99, 0xa1, 0xe8, 0xa2, 0x8c, 0x02, 0xb4, 0x6c);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("CodeGeneration.DSL.WorldHasAnimals/Element.DisplayName", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("CodeGeneration.DSL.WorldHasAnimals/Element.Description", typeof(global::CodeGeneration.DSL.DSLDomainModel), "CodeGeneration.DSL.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "World", PropertyDisplayNameKey="CodeGeneration.DSL.WorldHasAnimals/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("3224416b-0762-4a1a-99a1-e8a28c02b46c")]
		internal virtual Animal Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Animal)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Animals of a World
		/// <summary>
		/// Gets a list of Animals.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static DslModeling::LinkedElementCollection<Animal> GetAnimals(World element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Animal>, Animal>(element, WorldDomainRoleId);
		}
		#endregion
		#region World link accessor
		/// <summary>
		/// Get the list of WorldHasAnimals links to a World.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static global::System.Collections.ObjectModel.ReadOnlyCollection<global::CodeGeneration.DSL.WorldHasAnimals> GetLinksToAnimals ( global::CodeGeneration.DSL.World worldInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::CodeGeneration.DSL.WorldHasAnimals>(worldInstance, global::CodeGeneration.DSL.WorldHasAnimals.WorldDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the WorldHasAnimals link to a Animal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static global::CodeGeneration.DSL.WorldHasAnimals GetLinkToWorld (global::CodeGeneration.DSL.Animal elementInstance)
		{
			global::System.Collections.Generic.IList<global::CodeGeneration.DSL.WorldHasAnimals> links = DslModeling::DomainRoleInfo.GetElementLinks<global::CodeGeneration.DSL.WorldHasAnimals>(elementInstance, global::CodeGeneration.DSL.WorldHasAnimals.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region WorldHasAnimals instance accessors
		
		/// <summary>
		/// Get any WorldHasAnimals links between a given World and a Animal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static global::System.Collections.ObjectModel.ReadOnlyCollection<global::CodeGeneration.DSL.WorldHasAnimals> GetLinks( global::CodeGeneration.DSL.World source, global::CodeGeneration.DSL.Animal target )
		{
			global::System.Collections.Generic.List<global::CodeGeneration.DSL.WorldHasAnimals> outLinks = new global::System.Collections.Generic.List<global::CodeGeneration.DSL.WorldHasAnimals>();
			global::System.Collections.Generic.IList<global::CodeGeneration.DSL.WorldHasAnimals> links = DslModeling::DomainRoleInfo.GetElementLinks<global::CodeGeneration.DSL.WorldHasAnimals>(source, global::CodeGeneration.DSL.WorldHasAnimals.WorldDomainRoleId);
			foreach ( global::CodeGeneration.DSL.WorldHasAnimals link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one WorldHasAnimals link between a given Worldand a Animal.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		internal static global::CodeGeneration.DSL.WorldHasAnimals GetLink( global::CodeGeneration.DSL.World source, global::CodeGeneration.DSL.Animal target )
		{
			global::System.Collections.Generic.IList<global::CodeGeneration.DSL.WorldHasAnimals> links = DslModeling::DomainRoleInfo.GetElementLinks<global::CodeGeneration.DSL.WorldHasAnimals>(source, global::CodeGeneration.DSL.WorldHasAnimals.WorldDomainRoleId);
			foreach ( global::CodeGeneration.DSL.WorldHasAnimals link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
