//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.DSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "model";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CodeGeneration";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string DSLPackageId = "47ca2df8-e553-45a3-b4e8-5a49bba3c66f";
		
		// Editor factory identifier
		public const string DSLEditorFactoryId = "6efc3e1d-65d4-41b8-8e36-f6ae4ac5cce7";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DSLModelExplorerToolWindowId = "aa89f8f3-fdbc-4e6b-b8a7-85151cd909ed";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace CodeGeneration.DSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DSLCommandSetId = "f9c31293-951d-40f2-bf98-1eb3b587ba61";
	}
}